apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels: 
    {{- include "helmcharts.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
     matchLabels:
        {{- include "helmcharts.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "helmcharts.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.container.name }}
          image: {{ .Values.image.repository | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
